blank_issues_enabled: false
contact_links:
  - name: 📘 Documentation
    url: https://astro-pure.js.org/docs
    about: Checkout the documentation for more information
  - name: 💁 Discussion
    url: https://github.com/chiffonng/blog-astro/discussions
    about: 'This issue tracker is not for support questions. Leave a comment on the discussion board if you need help.'
