export { default as aboutSchema } from './about'
export { default as blogSchema } from './blog'
export { default as contactsSchema } from './contacts'
export { default as educationSchema } from './education'
export { default as projectsSchema } from './projects'
